### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_url-name is deffering.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#10]
**Defect Description**:
In all the pages of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, the numbering of the lab in the URL is given as 4. Where as this is the 5th lab in the list of experiments.

**Actual Result**:
In all the pages of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, the numbering of the lab in the URL is given as 4.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_url 5 _i9](https://cloud.githubusercontent.com/assets/13479177/18903585/698037b2-8573-11e6-9df8-65b201e654a0.png)

**Comment by sravanthimodepu** [comment]
As the labs are running on open-edx, there is no need of numbering for the experiment. They are given with experiment names.

**Comment by BSravanthi** [comment]
Closed #10
