### ISSUE TITLE
QA_Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems_url_name is differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#11]
**Defect Description**:
In all the pages of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment in this lab, the numbering of the lab in the URL is given as 5. Where as this is the 6th lab in the list of experiments.

**Actual Result**:
In all the pages of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment in this lab, the numbering of the lab in the URL is given as 5.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_url 6 _i10](https://cloud.githubusercontent.com/assets/13479177/18903878/e0e1ec3c-8574-11e6-83bd-007725467625.png)

**Comment by sravanthimodepu** [comment]
As the labs are running on open-edx, there is no need of numbering for the experiment. They are given with experiment names.

**Comment by BSravanthi** [comment]
Closed #11
