### ISSUE TITLE
QA_Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems_references_unassigned links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#12]
**Defect Description**:
In the References page of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment in this lab, all the links mentioned in the page are unassigned. Need to assign the links for the reference. 

**Actual Result**:
In the References page of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment in this lab, all the links mentioned in the page are unassigned.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 6 _i11](https://cloud.githubusercontent.com/assets/13479177/18905229/93eef710-857b-11e6-9f06-be92de12df82.png)

**Comment by sravanthimodepu** [comment]
Assigned all the links in the references page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #12
