### ISSUE TITLE
QA_Gel Electrophoresis_references_unassigned links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#15]
**Defect Description**:
In the References page of " Gel Electrophoresis " experiment in this lab, all the links mentioned in the page are unassigned. Need to assign the links for the reference.

**Actual Result**:
In the References page of " Gel Electrophoresis " experiment in this lab, all the links mentioned in the page are unassigned.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 7 _i14](https://cloud.githubusercontent.com/assets/13479177/18907451/1fd226a4-8585-11e6-9c65-6919dcb07619.png)

**Comment by sravanthimodepu** [comment]
In this references links 9, 11 & 18 links are throughing an error saying "Page not found". Hence removed those links.

**Comment by BSravanthi** [comment]
Closed #15

**Comment by BSravanthi** [comment]
Issue is reopened as the 5th link is still unassigned.
