### ISSUE TITLE
QA_Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles_References_links redirectin to error page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#16]
**Defect Description**:
In the References page of "Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles" experiment in this lab, both the links mentioned in the page are leading to an error page. Need to correct the links for the reference.

**Actual Result**:
In the References page of "Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles" experiment in this lab, both the links mentioned in the page are leading to an error page.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 8 _i15](https://cloud.githubusercontent.com/assets/13479177/18907627/cff22f8e-8585-11e6-8367-aecb7ba81dd3.png)

**Comment by sravanthimodepu** [comment]
Assigned the proper link in the reference page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue yet to be fixed. Hence reopening.

**Comment by BSravanthi** [comment]
Assigned the proper link in the reference page. Issue is resolved.

**Comment by BSravanthi** [comment]
Closed #16
