### ISSUE TITLE
QA_Study of the Catalytic Effects of Finely Divided Particles_url-name is deffering.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#17]
**Defect Description**:
In all the pages of "Study of the Catalytic Effects of Finely Divided Particles" experiment in this lab, the numbering of the lab in the URL is given as 15. Where as this is the 9th lab in the list of experiments.

**Actual Result**:
In all the pages of "Study of the Catalytic Effects of Finely Divided Particles" experiment in this lab, the numbering of the lab in the URL is given as 15.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_url 9 _i16](https://cloud.githubusercontent.com/assets/13479177/18908466/2026bad0-8589-11e6-830d-c917e0d7b195.png)

**Comment by sravanthimodepu** [comment]
As the labs are running on open-edx, there is no need of numbering for the experiment. They are given with experiment names.

**Comment by BSravanthi** [comment]
Closed #17
