### ISSUE TITLE
QA_Preparation of Gels_Theory_improper-porting-of-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#20]
Defect Description :
In the Theory page of "Preparation of Gels" experiment in this lab, The images are shrunk.

Actual Result :
In the Theory page of "Preparation of Gels" experiment in this lab, The images are shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i02](https://cloud.githubusercontent.com/assets/13479177/26581283/741adf78-4559-11e7-8b04-f74ea8581054.png)

**Comment by sravanthimodepu** [comment]
Increased the size of images accordingly. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #20
