### ISSUE TITLE
QA_Preparation of Gels_Quiz_repeated-questions

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#22]
Defect Description :
in the Quiz section of Preparation of Gels experiment, same question is repeated twice in pre experiment unit. 

Actual Result :
in the Quiz section of Preparation of Gels experiment, same question is repeated twice in pre experiment unit. Refer attachments

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_csc_i04](https://cloud.githubusercontent.com/assets/13479177/26581689/6f2b4316-455b-11e7-9910-25932a0d0fc6.png)

**Comment by sravanthimodepu** [comment]
Removed the extra question which is listed twice. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #22
