### ISSUE TITLE
QA_Demonstration of the Preparation and Use of Association Colloids (Micelles)_Theory_figure

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#23]
Defect Description :
In the Theory page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, in the 3rd paragraph's content, mentioned that **Figure 1. Schematic representations of structures of (a) a surfactant molecule, SDS, and its stick diagram and (b) a partial cross-sectional view of an aqueous (normal) micelle.** But as mentioned no figure is provided.

Actual Result :
In the Theory page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, in the 3rd paragraph's content, mentioned that **Figure 1. Schematic representations of structures of (a) a surfactant molecule, SDS, and its stick diagram and (b) a partial cross-sectional view of an aqueous (normal) micelle.** But as mentioned no figure is provided.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i05](https://cloud.githubusercontent.com/assets/13479177/26581976/b6275466-455c-11e7-80ee-7d8400fbfd32.png)

**Comment by sravanthimodepu** [comment]
There is no figure in vlab.co.in page to port the image.

**Comment by BSravanthi** [comment]
Closed #23
