### ISSUE TITLE
QA_Demonstration of the Preparation and Use of Association Colloids (Micelles)_Quiz_need-to-port-all-the-question

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#24]
Defect Description :
In the Quiz page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, all the questions in post experiment section has not been included while porting.

Actual Result :
In the Quiz page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, all the questions in post experiment section has not been included while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i06](https://cloud.githubusercontent.com/assets/13479177/26618094/73d8c082-45f6-11e7-9a90-c5f993af0dec.png)

**Comment by sravanthimodepu** [comment]
Ported all the questions in the quiz. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #24
