### ISSUE TITLE
QA_Demonstration of the Preparation and Use of Association Colloids (Micelles)_references_unassigned-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#25]
Defect Description :
In the References page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, all the links are unassigned.

Actual Result :
In the References page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, all the links are unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i07](https://cloud.githubusercontent.com/assets/13479177/26618169/f0f6f958-45f6-11e7-9303-78889ca0e7e0.png)

**Comment by sravanthimodepu** [comment]
Assigned links in the references page. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #25
