### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_Introduction_improper-porting-of-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#26]
Defect Description :
In the Introduction page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, The images are shrunk.

Actual Result :
In the Introduction page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, The images are shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe-csc_i08](https://cloud.githubusercontent.com/assets/13479177/26618329/ab46d95e-45f7-11e7-894c-5b591cda506e.png)

**Comment by sravanthimodepu** [comment]
Adjusted the lengt and width of the image to view in a better way. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #26
