### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_menu_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#27]
Defect Description :
In the menu bar of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment of this lab, references spelling is given wrong.

Actual Result :
In the menu bar of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment of this lab, references spelling is given wrong.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i09](https://cloud.githubusercontent.com/assets/13479177/26618550/5c47d82a-45f8-11e7-9220-d4482b3416da.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #27
