### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_Procedure_table-format-is-incomplete

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#28]
Defect Description :
In the procedure page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, The table has not been ported completely. 

Actual Result :
In the procedure page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, The table has not been ported completely. Part of the table is missed.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i10](https://cloud.githubusercontent.com/assets/13479177/26618778/4006f41a-45f9-11e7-8ba3-ce8a6eee04ab.png)

**Comment by sravanthimodepu** [comment]
Added rows to the table accordingly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #28
