### ISSUE TITLE
QA_Demonstration of the Preparation and Use of Association Colloids (Micelles)_procedure_section-is-unavailable

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#29]
Defect Description :
In the "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment of this lab, procedure section is not available. Where as in other the procedure section is provided.

Actual Result :
In the "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment of this lab, procedure section is not available. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i11](https://cloud.githubusercontent.com/assets/13479177/26619062/6f6dde66-45fa-11e7-8ffe-9df1bc72244f.png)

**Comment by sravanthimodepu** [comment]
Procedure is not given in vlab.co.in. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #29
