### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_Theory_improper-porting-of-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#30]
Defect Description :
In the Theory page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, The images are shrunk.

Actual Result :
In the Theory page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, The images are shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i12](https://cloud.githubusercontent.com/assets/13479177/26619383/dbd32402-45fb-11e7-87ee-6ba32804c3c7.png)

**Comment by sravanthimodepu** [comment]
Adjusted height and width for the images to view in a better way. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #30
