### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_Theory_unassigned-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#31]
Defect Description :
In the Theory page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment of this lab, The link given below the image is unassigned. 

Actual Result :
In the Theory page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment of this lab, The link given below the image is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i13](https://cloud.githubusercontent.com/assets/13479177/26619436/180292a0-45fc-11e7-9cac-fa8881100084.png)

**Comment by sravanthimodepu** [comment]
Assigned appropriate link in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still not fixed. Hence reopening.

**Comment by sravanthimodepu** [comment]
Updated the proper link to the above mentioned theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #31
