### ISSUE TITLE
QA_Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems_References_unassigned-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#32]
Defect Description :
In the References page of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment of this lab, The link given below the image is unassigned.

Actual Result :
In the Theory page of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment of this lab, The link given below the image is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i14](https://cloud.githubusercontent.com/assets/13479177/26620130/1eb1f296-45ff-11e7-9b61-8a81d351bbd1.png)

**Comment by sravanthimodepu** [comment]
Assigned links accordingly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #32
