### ISSUE TITLE
QA_Gel Electrophoresis_Object_UI

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#33]
Defect Description :
In the Objective page of "Gel Electrophoresis" experiment of this lab, The alignment of the content can be given better. 

Actual Result :
In the Objective page of "Gel Electrophoresis" experiment of this lab, The alignment of the content can be given better. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i15](https://cloud.githubusercontent.com/assets/13479177/26620308/f3991e6c-45ff-11e7-906b-c0ab3bf8f0bb.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly. Hence the issue is resolved

**Comment by BSravanthi** [comment]
Reopening the issue.

**Comment by sravanthimodepu** [comment]
Aligned the objective content properly and the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #33
