### ISSUE TITLE
QA_Gel Electrophoresis_Theory_table-format-is-incomplete

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#34]
Defect Description :
In the theory page of "Gel Electrophoresis" experiment in this lab, The table has not been ported completely.

Actual Result :
In the theory page of "Gel Electrophoresis" experiment in this lab, The table has not been ported completely.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i17](https://cloud.githubusercontent.com/assets/13479177/26620439/7957a8ac-4600-11e7-9f82-7aa15cac7c97.png)

**Comment by sravanthimodepu** [comment]
Added columns to the table. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #34
