### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_simulator_improper-alignment-of-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#35]
Defect Description :
In the experiment section of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment, the alignment of the experiment in the small screen is improper. Due to this the display of the whole experiment is not present. Where as in the full screen the complete experiment is visible.

Actual Result :
In the experiment section of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment, the alignment of the experiment in the small screen is improper. Due to this the display of the whole experiment is not present. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i01](https://user-images.githubusercontent.com/13479177/27370412-16d79e14-567a-11e7-9376-af1de7e94283.png)

**Comment by sravanthimodepu** [comment]
As the simulations is running with flash, we cannot make any changes to it. Will modify the simulation while doing conversion from flash to javascript.
