### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_simulator_flow-in-the-slider-bar-is-missing

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#36]
Defect Description :
In the experiment section of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment, the functionality of the slide bar is improper. FLow of the functionality is missing.

Actual Result :
In the experiment section of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment, the functionality of the slide bar is improper. FLow of the functionality is missing.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

**Comment by sravanthimodepu** [comment]
As the simulation runs with flash, we cannot make any changes to it. Will modify the simulation while doing the conversion.
