### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_simulator_improper-alignment-of-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#37]
Defect Description :
In the experiment section of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment, the alignment of the experiment in the small screen is improper. Due to this the display of the whole experiment is not present. Where as in the full screen the complete experiment is visible.

Actual Result :
In the experiment section of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment, the alignment of the experiment in the small screen is improper. Due to this the display of the whole experiment is not present.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i02](https://user-images.githubusercontent.com/13479177/27373288-59af3098-5685-11e7-9f8b-37b5bfe3ae5d.png)

**Comment by sravanthimodepu** [comment]
As the simulation is not aligned properly in the page, unable to adjust it, Hence we can make changes wile doing conversion from flash to javascript.
