### ISSUE TITLE
QA_Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems_simulator_radio-buttons-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#38]
Defect Description :
In the experiment section of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment, the functionality of the radio buttons is inconsistent. While we check the Tyndall effect of the each solution by clicking on the radio buttons, the buttons are not been un selected for the next solution. Where as for every solution the result window should pop up with un selected radio buttons. 

Actual Result :
In the experiment section of "Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems" experiment, the functionality of the radio buttons is inconsistent. While we check the Tyndall effect of the each solution by clicking on the radio buttons, the buttons are not been un selected for the next solution. Where as for every solution the result window should pop up with un selected radio buttons. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i03](https://user-images.githubusercontent.com/13479177/27377094-9ee83a9a-5691-11e7-812a-b2bad02a4223.png)

**Comment by sravanthimodepu** [comment]
As the simulation runs with flash, we cannot make any changes to it. Will modify the simulation while doing conversion from flash to javscript.
