### ISSUE TITLE
QA_Demonstration of the Preparation and Use of Association Colloids (Micelles)_references_Broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#39]
Defect Description :
While testing #25 In the References page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, found that the 3rd link is broken.

Actual Result :
While testing #25 In the References page of "Demonstration of the Preparation and Use of Association Colloids (Micelles)" experiment in this lab, found that the 3rd link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i18](https://user-images.githubusercontent.com/13479177/27469638-4200ab4a-580e-11e7-907c-458f50fe3caf.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link for the above mentioned references. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #39
