### ISSUE TITLE
QA_Preparation of Gels_References_Broken and repeated links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#4]
**Defect Description**:
In the References page of "Preparation of Gels" experiment in this lab, the 3rd, 6th, 13th and 17th links are broken. And the 4th and the 15th links are same. Need to remove the repeated links and correct the broken links.

**Actual Result**:
In the References page of "Preparation of Gels" experiment in this lab, the 3rd, 6th, 13th and 17th links are broken. And the 4th and the 15th links are same.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 2 _i2](https://cloud.githubusercontent.com/assets/13479177/18869678/c7a2feb8-84c6-11e6-9781-66a0a382c8f6.png)

**Comment by sravanthimodepu** [comment]
Updated the links with proper URL. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Re opening as the issue is still persisting.

**Comment by sravanthimodepu** [comment]
As  3rd, 6th & 13th links are not available, hiding those links. And removing the 15th link, as 4th and 15th are assigned with the same link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue as the 10th and 11th links are navigating to same page.

**Comment by sravanthimodepu** [comment]
Removed one link, as they are same links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #4
