### ISSUE TITLE
QA_Gel Electrophoresis_references_broken-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#40]
Defect Description :
While testing #15 In the References page of "Gel Electrophoresis" experiment in this lab, found that the 3rd link is broken. 

Actual Result :
While testing #15 In the References page of "Gel Electrophoresis" experiment in this lab, found that the 3rd link is broken. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_csc_i19](https://user-images.githubusercontent.com/13479177/27473251-15794948-581c-11e7-81ae-b9eae1ed6c52.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link in the references. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #40
