### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_url_name is differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#5]
**Defect Description**:
In all the pages of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, the numbering of the lab in the URL is given as 14. Where as this is the 4th lab in the list of experiments.

**Actual Result**:
In all the pages of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, the numbering of the lab in the URL is given as 14.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_url 4 _i4](https://cloud.githubusercontent.com/assets/13479177/18901731/06d0c4d0-8567-11e6-891c-a3797935cfa7.png)

**Comment by sravanthimodepu** [comment]
As all the labs are on Open-edx, there is  no need of numbering for the experiment. All the experiments are listed with experiment names.

**Comment by BSravanthi** [comment]
CLOSED #5
