### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant_Simulation

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#6]
**Defect Description**:
In the Simulation page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, at the end of the each observation the sample solution is poured in to the another beaker with the help of conductivity cell. After this the beaker is disappearing and the sample solution is appearing on the screen for fraction of second, then the solution is also disappearing. Where as the desired result should be the solution and the beaker should be disappeared at a time. 

**Actual Result**:
In the Simulation page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant" experiment in this lab, at the end of the each observation the sample solution is poured in to the another beaker with the help of conductivity cell. After this the beaker is disappearing and the sample solution is appearing on the screen for fraction of second, then the solution is also disappearing. 

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_simu 4 _i5](https://cloud.githubusercontent.com/assets/13479177/18902303/7df874be-856b-11e6-85f1-447adbd0fb72.png)

**Comment by sravanthimodepu** [comment]
Cannot change the simulation as it is running with flash. We can modify the simulation accordingly while doing the conversion from Flash to JavaScript.
