### ISSUE TITLE
QA_Determination of Critical Micelle Concentration (CMC) of a Surfactant _references_page redirecting to error page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#7]
**Defect Description**:
In the References page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant " experiment in this lab, the 4th link is redirecting to an error page showing the massage "page not found". Need to correct the link to give better information to the user.

**Actual Result**:
In the References page of "Determination of Critical Micelle Concentration (CMC) of a Surfactant " experiment in this lab, the 4th link is redirecting to an error page showing the massage "page not found". 

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 4 _i6](https://cloud.githubusercontent.com/assets/13479177/18902558/2dc8f41c-856d-11e6-89d6-1838f3cdef7f.png)

**Comment by sravanthimodepu** [comment]
Updated the proper link. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Still the issue persists. Hence opened the issue.

**Comment by BSravanthi** [comment]
Assigned the appropriate link. Issue is fixed

**Comment by BSravanthi** [comment]
Closed #7
