### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_Simulation

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/colloid-and-surface-chemistry-iiith#8]
**Defect Description**:
In the Simulation page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, all the apparatus are staying back on the experiment table after their performance. Where as these apparatus should go back to the shelf after performing their work. 

And once the beaker, talcum powder and detergent are selected from the shelf they are still appearing on the shelf even after the beaker, talcum power and the detergent is present on the table. 

**Actual Result**:
In the Simulation page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents" experiment in this lab, all the apparatus are staying back on the experiment table after their performance.

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_simu 5 _i7](https://cloud.githubusercontent.com/assets/13479177/18903019/16cbd63c-8570-11e6-9f30-38c8cf949192.png)

**Comment by sravanthimodepu** [comment]
As the simulation is running with flash, we cannot change apparatus in the flash. We may change the simulation while doing conversion.
