### ISSUE TITLE
QA_Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents_References_page redirecting to an error page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/colloid-and-surface-chemistry-iiith#9]
**Defect Description**:
In the References page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents " experiment in this lab, the 3rd link is redirecting to an error page. Instead the link should be redirected to an appropriate for the advantage of the user.

**Actual Result**:
In the References page of "Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents " experiment in this lab, the 3rd link is redirecting to an error page. 

**Environment**:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_csc_ref 5 _i8](https://cloud.githubusercontent.com/assets/13479177/18903331/edbb5f04-8571-11e6-8f1d-01387c2095c1.png)

**Comment by sravanthimodepu** [comment]
Link is updated correctly.Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #9
